/**
 * Tech Quest — Expansión de contenido (se aplica sobre WORLDS de data.js)
 * Prioridad: Impresoras y Redes profundos + bosses + mundo 6 Soporte IT
 */
(function expandContent() {
  function add(worldId, questions) {
    const w = getWorldById(worldId);
    if (!w) return;
    w.questions = w.questions.concat(questions);
  }

  function setBoss(worldId, bossQs) {
    const w = getWorldById(worldId);
    if (!w) return;
    w.boss = bossQs;
  }

  // ——— Linux extras ———
  add("linux", [
    { id: "lx13", type: "tf", q: "En Linux, el usuario root tiene UID 1000.", answer: false, explain: "Falso: root siempre tiene UID 0. Los UID desde 1000 (en la mayoría de distros) son usuarios normales." },
    { id: "lx14", type: "mc", q: "¿Qué hace el comando df -h?", options: ["Muestra espacio en discos montados de forma legible", "Muestra el tamaño de cada carpeta de forma legible", "Muestra la RAM y la swap libres de forma legible", "Revisa y repara el sistema de archivos del disco"], answer: 0, explain: "df = disk free. -h muestra tamaños en K/M/G." },
    { id: "lx15", type: "fill", q: "Comando para ver las últimas líneas de /var/log/syslog (forma corta con tail):", answer: "tail /var/log/syslog", accept: ["tail /var/log/syslog", "tail -n 10 /var/log/syslog", "tail -n10 /var/log/syslog", "tail -10 /var/log/syslog", "tail -f /var/log/syslog", "sudo tail /var/log/syslog", "sudo tail -n 10 /var/log/syslog", "sudo tail -f /var/log/syslog", "sudo tail -n10 /var/log/syslog", "sudo tail -10 /var/log/syslog"], explain: "tail muestra el final del archivo. -f sigue el log en vivo." },
    { id: "lx16", type: "scenario", q: "Escenario: necesitas matar el proceso con PID 4421. ¿Qué comando usas?", options: ["kill 4421", "rm 4421", "chmod 4421", "apt remove 4421"], answer: 0, explain: "kill envía una señal (por defecto TERM). kill -9 fuerza SIGKILL si no responde." },
    { id: "lx17", type: "mc", q: "¿Qué archivo contiene la lista de cuentas de usuario locales del sistema?", options: ["/etc/passwd", "/etc/hosts", "/etc/fstab", "/etc/hostname"], answer: 0, explain: "/etc/passwd describe cuentas; las contraseñas hasheadas van en /etc/shadow." },
    { id: "lx18", type: "identify", q: "¿Qué comando muestra el uso de memoria RAM y swap?", options: ["free", "mkdir", "ping", "lpstat"], answer: 0, explain: "free -h resume memoria. También puedes verlo en top/htop." }
  ]);

  // ——— Windows extras ———
  add("windows", [
    { id: "wn13", type: "tf", q: "Win+R → services.msc abre la consola de servicios.", answer: true, explain: "services.msc es el snap-in clásico para iniciar/detener/reiniciar servicios." },
    { id: "wn14", type: "scenario", q: "Escenario: la caché DNS está corrupta. ¿Qué comando la limpia?", options: ["ipconfig /flushdns", "ipconfig /displaydns", "netsh winsock reset", "ipconfig /release"], answer: 0, explain: "ipconfig /flushdns vacía el resolver cache de Windows." },
    { id: "wn15", type: "mc", q: "RDP (Escritorio remoto) usa por defecto el puerto TCP…", options: ["3389", "22", "445", "9100"], answer: 0, explain: "3389 es el puerto clásico de Remote Desktop. Debe estar permitido en el firewall." },
    { id: "wn16", type: "fill", q: "Comando de PowerShell (cmdlet y nombre del servicio) para reiniciar el servicio Spooler:", answer: "Restart-Service Spooler", accept: ["Restart-Service Spooler", "Restart-Service -Name Spooler", "Restart-Service Spooler -Force", "Restart-Service -Force Spooler", "Restart-Service -Name Spooler -Force", "Restart-Service -Force -Name Spooler", "Restart-Service 'Spooler'", "Restart-Service \"Spooler\"", "Restart-Service -Name 'Spooler'", "Restart-Service -Name \"Spooler\"", "Restart-Service 'Spooler' -Force", "Get-Service Spooler | Restart-Service", "Get-Service Spooler | Restart-Service -Force", "Get-Service -Name Spooler | Restart-Service", "Restart-Service \"Spooler\" -Force", "Restart-Service -Name 'Spooler' -Force", "Restart-Service -Name \"Spooler\" -Force", "Get-Service -Name Spooler | Restart-Service -Force", "Restart-Service -Force 'Spooler'", "Restart-Service -Force \"Spooler\"", "Restart-Service -Force -Name 'Spooler'", "Restart-Service -Force -Name \"Spooler\""], explain: "Restart-Service detiene e inicia el servicio (suele requerir consola elevada). Si el servicio tiene dependientes (p. ej., Fax), añade -Force." },
    { id: "wn17", type: "order", q: "Ordena un diagnóstico cuando un PC no llega a Internet pero sí hace ping a 8.8.8.8:", items: ["Verificar DNS (ipconfig /all)", "Probar resolución nslookup sitio.com", "Si nslookup falla, cambiar a otro DNS (1.1.1.1 / 8.8.8.8)", "Tras cambiar el DNS, vaciar la caché de resolución y volver a probar"], answer: [0, 1, 2, 3], explain: "Si hay IP pero no nombres, el problema suele ser DNS: revisa qué DNS usa el equipo, prueba la resolución con nslookup, cambia a un DNS alternativo si falla y limpia la caché para descartar respuestas viejas." },
    { id: "wn18", type: "mc", q: "¿Qué herramienta abre el Editor del Registro?", options: ["regedit", "mspaint", "calc", "notepad únicamente"], answer: 0, explain: "regedit edita el registro. Cámbialo solo con respaldo y conocimiento: errores pueden romper el sistema." }
  ]);

  // ——— IMPRESORAS: profundidad intermedia→avanzada (meta ≥20 total) ———
  add("printers", [
    { id: "pr13", type: "mc", q: "El puerto TCP 9100 suele asociarse a…", options: ["Impresión raw / JetDirect", "Monitoreo SNMP del estado del equipo", "Descubrimiento mDNS / Bonjour", "Servidor web embebido (EWS)"], answer: 0, explain: "Muchas impresoras de red aceptan trabajos en 9100 (AppSocket/JetDirect). IPP suele usar 631, SNMP 161/UDP, mDNS 5353/UDP y el portal web 80/443." },
    { id: "pr14", type: "mc", q: "Diferencia introductoria PCL vs PostScript:", options: ["PCL (HP) y PS (Adobe) son lenguajes de descripción de página; el driver debe coincidir", "PCL solo funciona en Mac y PostScript solo en impresoras de inyección de tinta", "Son protocolos de red: PCL usa el puerto 9100 y PostScript el puerto 631", "Son formatos de cartucho: PCL para tóner negro y PostScript para color"], answer: 0, explain: "Si eliges el lenguaje incorrecto verás caracteres basura o trabajos fallidos. Algunas MFP soportan ambos." },
    { id: "pr15", type: "tf", q: "LPR/LPD usa normalmente el puerto 9100.", answer: false, explain: "Falso: LPR/LPD usa el puerto 515; el 9100 es RAW/JetDirect. Hoy IPP (631) es la opción más moderna." },
    { id: "pr16", type: "scenario", q: "Escenario: varios usuarios imprimen vía un servidor Windows. ¿Concepto clave?", options: ["Print server / cola compartida en el servidor", "Cada uno debe usar solo USB al mismo tiempo", "Desactivar el Spooler del servidor siempre", "Mapear una unidad de red con la IP de la impresora"], answer: 0, explain: "El print server centraliza drivers y colas; los clientes apuntan al recurso compartido \\\\servidor\\impresora." },
    { id: "pr17", type: "mc", q: "Impresión por SMB significa típicamente…", options: ["Compartir la impresora como recurso de red Windows (\\\\host\\share)", "Enviar el documento por correo SMTP a la dirección de la impresora", "Enviar trabajos raw al puerto TCP 9100 del dispositivo", "Descubrir la impresora vía mDNS/Bonjour e imprimir por IPP"], answer: 0, explain: "SMB/CIFS expone la cola como \\\\servidor\\impresora. Útil en dominios; requiere permisos correctos en la pestaña Seguridad de la impresora compartida." },
    { id: "pr18", type: "order", q: "Ordena el flujo para limpiar una cola atascada (Windows):", items: ["Detener el servicio Print Spooler", "Vaciar archivos en spool\\PRINTERS (con cuidado)", "Iniciar de nuevo Print Spooler", "Reenviar una página de prueba"], answer: [0, 1, 2, 3], explain: "Nunca borres el spool con el servicio en ejecución: puede corromper estados." },
    { id: "pr19", type: "mc", q: "¿Qué es el tambor (drum) en una láser?", options: ["Pieza fotosensible que transfiere tóner al papel; a veces se desgasta aparte del cartucho", "Rodillo térmico (fusor) que funde el tóner sobre el papel con calor y presión", "Depósito que recoge el tóner sobrante; en algunos modelos va aparte del cartucho", "Rodillo de goma que toma las hojas de la bandeja y las arrastra al interior"], answer: 0, explain: "En kits separados, tóner bajo ≠ drum agotado. Rayas o manchas pueden indicar drum sucio/agotado." },
    { id: "pr20", type: "identify", q: "¿Qué comando/utilidad en Windows lista impresoras y colas (línea de comandos clásica)?", options: ["wmic printer / PowerShell Get-Printer", "tasklist / PowerShell Get-Process", "wmic diskdrive / PowerShell Get-Disk", "netstat / PowerShell Get-NetTCPConnection"], answer: 0, explain: "Get-Printer (PowerShell) o la UI de Impresoras y escáneres. lpstat en Linux/CUPS." },
    { id: "pr21", type: "fill", q: "Puerto típico de IPP (número):", answer: "631", accept: ["631"], explain: "IPP (Internet Printing Protocol) usa 631/tcp de forma habitual." },
    { id: "pr22", type: "mc", q: "Descubrimiento de impresoras en LAN moderna a menudo usa…", options: ["mDNS / WS-Discovery / SNMP según fabricante", "FTP anónimo / TFTP / Telnet según fabricante", "NTP / Syslog / RADIUS según fabricante", "RDP / VNC / SSH según fabricante"], answer: 0, explain: "Bonjour/mDNS, WSD y portales web del dispositivo ayudan a 'ver' la impresora. Firewalls pueden ocultarla." },
    { id: "pr23", type: "scenario", q: "Escenario: la impresora Wi‑Fi está en otra VLAN/SSID de invitados. Los PCs corporativos no la ven. Causa más probable:", options: ["Aislamiento de red / sin routing entre VLANs", "Driver PCL incompatible en los PCs corporativos", "Cola del Spooler pausada en los PCs corporativos", "Firmware de la impresora pendiente de actualizar"], answer: 0, explain: "Impresoras en guest Wi‑Fi suelen estar aisladas. Ponla en la LAN de trabajo o enruta/firewall con reglas." },
    { id: "pr24", type: "mc", q: "Prioridad de trabajos en cola sirve para…", options: ["Definir qué trabajos se procesan antes (urgente vs normal)", "Limitar cuántas páginas puede imprimir cada usuario al mes", "Elegir qué bandeja de papel usa cada trabajo (A4 vs carta)", "Repartir los trabajos entre varias impresoras iguales (pooling)"], answer: 0, explain: "En print servers puedes asignar prioridad a usuarios/colas para tickets críticos." },
    { id: "pr25", type: "match", q: "Relaciona síntoma con causa frecuente:", pairs: [
      { left: "Página en blanco", right: "Tóner vacío o sello protector" },
      { left: "Atasco repetido", right: "Rodillos / papel húmedo / ruta" },
      { left: "Caracteres basura", right: "Driver/lenguaje incorrecto" },
      { left: "Offline en red", right: "IP/puerto/firewall/Spooler" }
    ], explain: "Separa hardware (papel/tóner) de lógica (driver/red/cola)." },
    { id: "pr26", type: "tf", q: "En una impresora compartida conviene dejar la IP por DHCP dinámico, sin reserva.", answer: false, explain: "Falso: si la IP cambia, los puertos TCP/IP de los clientes se rompen. Usa una reserva DHCP o una IP estática." },
    { id: "pr27", type: "mc", q: "Error de 'acceso denegado' al imprimir en cola compartida suele indicar…", options: ["Permisos de la impresora compartida (pestaña Seguridad), grupos o GPO", "Puerto TCP 9100 bloqueado por firewall entre print server e impresora", "Driver PCL incorrecto instalado en el equipo del cliente", "Certificado HTTPS caducado en el portal web de la impresora"], answer: 0, explain: "Revisa grupo Usuarios de dominio, permisos de la impresora compartida y GPO." },
    { id: "pr28", type: "order", q: "Ticket: no imprime por red. Ordena el diagnóstico técnico:", items: ["Ping a la IP de la impresora", "Probar puerto (9100/631) o página web embebida", "Verificar cola/Spooler en el PC o print server", "Reinstalar/actualizar driver correcto"], answer: [0, 1, 2, 3], explain: "Sin capa 3 no hay cola útil. Luego servicio local, luego driver." }
  ]);

  // ——— REDES: profundidad (meta ≥22 total) ———
  add("networks", [
    { id: "net14", type: "mc", q: "¿Cuántos hosts útiles aprox. en una red /24 (sin contar red y broadcast)?", options: ["254", "24", "512", "2"], answer: 0, explain: "2^(32-24)-2 = 254. Ejemplo: 192.168.1.0/24 → .1–.254." },
    { id: "net15", type: "mc", q: "Una máscara /16 equivale a…", options: ["255.255.0.0", "255.255.255.0", "255.255.255.252", "255.0.0.0"], answer: 0, explain: "/16 = 16 bits de red. Clase B típica en notación antigua." },
    { id: "net16", type: "order", q: "Ordena el proceso DHCP DORA:", items: ["Discover", "Offer", "Request", "Acknowledge (ACK)"], answer: [0, 1, 2, 3], explain: "Cliente descubre → servidor ofrece → cliente pide → servidor confirma el lease." },
    { id: "net17", type: "order", q: "Ordena la resolución DNS típica en el cliente:", items: ["Consultar caché local", "Preguntar al resolver (DNS configurado)", "Recibir registro A/AAAA (IP)", "Conectar por TCP/UDP al destino"], answer: [0, 1, 2, 3], explain: "Si la caché tiene la respuesta, no sale a la red. Luego el resolver puede iterar/recursar." },
    { id: "net18", type: "mc", q: "NAT (Network Address Translation) principalmente…", options: ["Traduce IPs privadas a una IP pública (u otras redes)", "Asigna IPs privadas a los equipos de la LAN de forma dinámica", "Resuelve nombres de dominio a las IPs públicas de los servidores", "Cifra el tráfico entre la red privada y la pública con un túnel"], answer: 0, explain: "PAT/NAT overload permite muchos hosts internos con pocas IPs públicas. Complica servicios entrantes sin port-forward." },
    { id: "net19", type: "match", q: "Relaciona puerto con servicio:", pairs: [
      { left: "80", right: "HTTP" },
      { left: "443", right: "HTTPS" },
      { left: "22", right: "SSH" },
      { left: "3389", right: "RDP" }
    ], explain: "9100 suele ser impresión raw; 53 DNS; 67/68 DHCP." },
    { id: "net20", type: "mc", q: "El puerto 9100 en un escaneo a una IP de oficina suele indicar…", options: ["Servicio de impresión de red (JetDirect/raw)", "Servidor de correo SMTP aceptando envíos", "Servicio de hora de red (NTP) del dominio", "Base de datos MySQL escuchando consultas"], answer: 0, explain: "Útil al validar que la impresora escucha. Bloqueado por firewall = no imprime aunque haga ping." },
    { id: "net21", type: "scenario", q: "Escenario: ping OK a 8.8.8.8 pero nslookup google.com falla. ¿Qué mirar primero?", options: ["Configuración DNS del cliente/servidor", "Puerta de enlace predeterminada del equipo", "Cable de red y luces del puerto del switch", "Máscara de subred del adaptador"], answer: 0, explain: "Hay ruta IP pero no resolución de nombres. Prueba DNS alternos y /flushdns." },
    { id: "net22", type: "mc", q: "Una VLAN sirve para…", options: ["Segmentar lógicamente la LAN en dominios de broadcast separados", "Cifrar el tráfico entre sedes a través de Internet mediante túneles", "Sumar el ancho de banda de varios enlaces físicos en uno lógico", "Evitar bucles de capa 2 bloqueando puertos redundantes del switch"], answer: 0, explain: "VLANs separan tráfico (ej. usuarios vs impresoras vs invitados) sobre el mismo switch físico." },
    { id: "net23", type: "tf", q: "WEP es más seguro que WPA3 para Wi‑Fi.", answer: false, explain: "Falso: WEP está obsoleto y se rompe en minutos. Usa WPA3 o, si no hay, WPA2-AES." },
    { id: "net24", type: "mc", q: "En 2.4 GHz, canales 1, 6 y 11 se recomiendan porque…", options: ["No se solapan entre sí en esa banda", "Son los únicos canales que permite la norma", "Transmiten con más potencia que el resto", "Son los canales de 40 MHz de esa banda"], answer: 0, explain: "En 2.4 GHz los canales están separados 5 MHz pero cada uno ocupa ~20-22 MHz; 1, 6 y 11 (25 MHz de separación) no se solapan. Usar canales intermedios causa interferencia de canal adyacente, peor que compartir canal (co-canal)." },
    { id: "net25", type: "fill", q: "Comando clásico para ver la ruta que siguen los paquetes (Windows):", answer: "tracert", accept: ["tracert", "tracert.exe"], explain: "tracert (Windows) / traceroute (Linux). Muestra saltos; timeouts no siempre = caída total." },
    { id: "net26", type: "mc", q: "Un proxy HTTP intermedio típicamente…", options: ["Reenvía peticiones web de clientes; puede cachear o filtrar", "Asigna direcciones IP a los clientes y renueva sus leases", "Conmuta tramas entre puertos usando la tabla de MACs", "Suministra energía PoE a teléfonos y cámaras IP de la red"], answer: 0, explain: "Empresas usan proxy para control/URL filtering. El cliente debe apuntar al proxy o usar WPAD." },
    { id: "net27", type: "mc", q: "Una CDN (Content Delivery Network)…", options: ["Acerca contenido a usuarios vía nodos geográficos (caché en edge)", "Centraliza todo el contenido en un único servidor de origen grande", "Registra nombres de dominio para los sitios web publicados en Internet", "Cifra el tráfico entre sucursales con túneles IPsec permanentes"], answer: 0, explain: "Reduce latencia y carga del origen. DNS/anycast dirige al PoP cercano." },
    { id: "net28", type: "scenario", q: "Escenario: PCs hacen ping entre sí en 192.168.10.0/24 pero no salen a Internet. Gateway 192.168.10.1 no responde. Causa probable:", options: ["Router/firewall de borde caído o mala gateway", "Servidor DNS de los PCs caído o mal configurado", "Tarjetas de red sin driver instalado", "Conflicto de IP duplicada entre dos de los PCs"], answer: 0, explain: "LAN OK, WAN/gateway mal. Verifica cable WAN, NAT, ISP y dirección de puerta de enlace." },
    { id: "net29", type: "mc", q: "ISP vs LAN:", options: ["ISP provee acceso a Internet; LAN es tu red local", "ISP es tu red local; LAN da acceso a Internet", "ISP es un cable de fibra; LAN es un protocolo web", "ISP asigna dominios; LAN es la Internet pública"], answer: 0, explain: "El CPE/router marca el límite: LAN privada detrás, WAN hacia el ISP." },
    { id: "net30", type: "mc", q: "Cat6 frente a Cat5e (idea práctica):", options: ["Cat6 da más margen en Gigabit y admite 10G en tramos cortos", "Cat5e admite 10G a 100 m; Cat6 se limita a 100 Mbps", "Cat6 usa conector RJ-11 y no es compatible con Gigabit", "Cat6 es fibra multimodo; Cat5e es coaxial de cobre"], answer: 0, explain: "Ambos hacen 1 Gbps en distancias típicas; Cat6 tiene especificación más estricta." },
    { id: "net31", type: "tf", q: "Un firewall puede permitir 443/tcp saliente y bloquear 3389/tcp entrante.", answer: true, explain: "Las reglas se definen por dirección, puerto, protocolo e interfaz. Principio de mínimo privilegio." },
    { id: "net32", type: "mc", q: "VPN con split tunnel significa…", options: ["Solo parte del tráfico va por la VPN; el resto sale por Internet local", "Todo el tráfico, incluida la navegación web, pasa siempre por la VPN", "El túnel se divide en dos conexiones cifradas con claves distintas", "La VPN se reparte entre dos concentradores para balancear la carga"], answer: 0, explain: "Full tunnel manda todo por VPN. Split mejora velocidad a Internet pero exige buen diseño de seguridad." },
    { id: "net33", type: "identify", q: "¿Qué herramienta interpreta saltos hasta un destino y latencias por hop?", options: ["mtr / pathping", "ipconfig / ifconfig", "nslookup / dig", "arp -a / ip neigh"], answer: 0, explain: "mtr (Linux) y pathping (Windows) muestran cada salto con su latencia y pérdida. Si el último hop falla pero el servicio web responde, puede ser ICMP filtrado — no asumas caída." },
    { id: "net34", type: "scenario", q: "Escenario: switch vs router. Necesitas conectar 20 PCs en la misma IP subnet sin salir a otra red. ¿Qué basta?", options: ["Un switch (capa 2) en la misma VLAN/red", "Un router con una subred distinta por cada PC", "Un proxy HTTP que reenvíe el tráfico entre ellos", "Un módem ONT del proveedor de Internet"], answer: 0, explain: "Misma subred = switching. El router hace falta para salir a otras redes/Internet." }
  ]);

  // ——— Programación extras ———
  add("programming", [
    { id: "pg14", type: "tf", q: "const en JavaScript hace que un objeto sea completamente inmutable.", answer: false, explain: "Falso: const solo impide reasignar la variable; las propiedades del objeto se pueden cambiar. Object.freeze lo congela (y solo de forma superficial)." },
    { id: "pg15", type: "scenario", q: "Escenario: quieres guardar cambios locales con mensaje. Flujo git mínimo:", options: ["git add → git commit -m \"mensaje\"", "git commit -m \"mensaje\" → git add", "git fetch → git merge origin/main", "git checkout -b cambios → git push"], answer: 0, explain: "add al stage, commit al historial local. push es opcional hacia remoto." },
    { id: "pg16", type: "mc", q: "¿Qué hace un bucle while?", options: ["Repite mientras la condición sea verdadera", "Ejecuta el bloque una sola vez si la condición es cierta", "Ejecuta el bloque en paralelo en varios hilos", "Declara una variable local dentro del bloque"], answer: 0, explain: "Cuidado con bucles infinitos: la condición debe poder volverse falsa." },
    { id: "pg17", type: "fill", q: "En JS, operador de igualdad estricta (valor y tipo):", answer: "===", accept: ["==="], explain: "=== no hace coerción. == puede convertir tipos y dar sorpresas." },
    { id: "pg18", type: "mc", q: "CSS: display: flex sirve para…", options: ["Crear layouts flexibles en una dimensión", "Ocultar el elemento sin quitarle su espacio", "Crear rejillas de filas y columnas a la vez", "Animar la transición entre dos estilos"], answer: 0, explain: "Flexbox alinea y distribuye espacio entre ítems de un contenedor." }
  ]);

  // ——— Mundo 6: Soporte IT ———
  if (!getWorldById("support")) {
    WORLDS.push({
      id: "support",
      name: "Soporte IT",
      icon: "🎫",
      color: "#ff7755",
      description: "Tickets, prioridades, soft skills y diagnóstico como en un help desk real.",
      questions: [
        { id: "su01", type: "mc", q: "En ITIL/help desk, un incidente es…", options: ["Interrupción no planificada o degradación de un servicio", "Causa raíz desconocida de uno o más incidentes recurrentes", "Petición estándar de alta o acceso de un usuario", "Modificación planificada y aprobada de un servicio en producción"], answer: 0, explain: "El objetivo es restaurar el servicio lo antes posible. Un problema es la causa raíz subyacente." },
        { id: "su02", type: "mc", q: "Prioridad de ticket suele combinar…", options: ["Impacto × urgencia", "Solo el color del logo", "La hora del almuerzo", "El volumen del teclado"], answer: 0, explain: "Alta urgencia + alto impacto = prioridad crítica (P1). Documenta SLAs." },
        { id: "su03", type: "order", q: "Ordena una atención telefónica profesional:", items: ["Saludar e identificarte", "Escuchar y confirmar el problema", "Diagnosticar / escalar si hace falta", "Cerrar con resumen y next steps"], answer: [0, 1, 2, 3], explain: "La empatía y la confirmación evitan malentendidos y rework." },
        { id: "su04", type: "scenario", q: "Usuario enfadado: '¡Nada funciona!'. Mejor primera respuesta:", options: ["Empatizar, pedir detalles concretos y reproducir", "Escalar a N3 de inmediato sin más preguntas", "Reiniciar su equipo en remoto antes de hacer preguntas", "Pedirle que abra un ticket nuevo por cada cosa que falla"], answer: 0, explain: "Baja la tensión, acota el alcance (¿solo Wi‑Fi? ¿una app?) y recoge evidencia." },
        { id: "su05", type: "tf", q: "Antes de cambiar algo en producción, conviene tener rollback o respaldo cuando sea posible.", answer: true, explain: "Cambios sin plan de vuelta atrás alargan las crisis." },
        { id: "su06", type: "mc", q: "¿Cuándo escalar a N2/N3?", options: ["Si excede tu alcance o el SLA, o requiere privilegios/especialistas", "Solo cuando el usuario lo pide o se queja con tu supervisor", "En cuanto entra el ticket, sin intentar ningún diagnóstico en N1", "Nunca: N1 debe cerrar todo él mismo aunque se incumpla el SLA"], answer: 0, explain: "Escala con contexto: qué se probó, logs, impacto, ventana de cambio." },
        { id: "su07", type: "match", q: "Relaciona severidad típica:", pairs: [
          { left: "P1", right: "Servicio crítico caído para muchos" },
          { left: "P3", right: "Impacto menor / workaround existe" },
          { left: "Request", right: "Petición de servicio (no incidente)" },
          { left: "Known error", right: "Causa conocida con workaround" }
        ], explain: "Clasificar bien acelera la cola correcta." },
        { id: "su08", type: "identify", q: "Documento breve de lo que hiciste en un ticket se llama…", options: ["Notas / resolución en el ticket (KB si aplica)", "Acuerdo de nivel de servicio (SLA) asociado al ticket", "Solicitud de cambio (RFC) ante el CAB", "Encuesta de satisfacción (CSAT) del usuario"], answer: 0, explain: "Buenas notas = menos reincidencia y mejores artículos de conocimiento." },
        { id: "su09", type: "fill", q: "Sigla común del acuerdo de nivel de servicio (inglés):", answer: "SLA", accept: ["SLA", "sla"], explain: "Service Level Agreement: tiempos de respuesta/resolución acordados." },
        { id: "su10", type: "mc", q: "Primera pregunta útil en 'no tengo Internet':", options: ["¿Es solo tu PC o más equipos? ¿Wi‑Fi o cable? ¿Hay IP?", "¿Qué versión de Office tienes? ¿Está activada la licencia?", "¿Me dices tu contraseña de red para probar desde aquí?", "¿Reinstalamos Windows ya? ¿Tienes copia de tus archivos?"], answer: 0, explain: "Aísla: local vs red vs ISP. Luego capa por capa." },
        { id: "su11", type: "scenario", q: "Ticket: impresora de piso no imprime; urgencia media. Ya hay ping OK. Siguiente paso razonable:", options: ["Revisar cola/Spooler/driver y página de prueba", "Escalar a redes para revisar el switch y la VLAN del piso", "Reemplazar la impresora por una nueva de inmediato", "Reinstalar Windows en el PC del usuario que reportó"], answer: 0, explain: "Red OK → capa de impresión. No amplíes el cambio innecesariamente." },
        { id: "su12", type: "tf", q: "Pedir captura del error y la hora exacta solo retrasa el ticket; basta con que el usuario diga 'no funciona'.", answer: false, explain: "Falso: la captura y la hora exacta permiten correlacionar con los logs del servidor y de eventos, y ahorran idas y vueltas." },
        { id: "su13", type: "mc", q: "Soft skill clave en soporte:", options: ["Comunicación clara y paciencia", "Gritar más fuerte", "Ocultar el estado del ticket", "Prometer milagros sin ETA"], answer: 0, explain: "Expectativas honestas + actualizaciones = confianza del usuario." },
        { id: "su14", type: "order", q: "Ordena el cierre de un incidente bien gestionado:", items: ["Confirmar con el usuario que el servicio volvió", "Documentar causa y solución en el ticket", "Crear KB / registrar problema si es recurrente", "Cerrar formalmente el ticket"], answer: [0, 1, 2, 3], explain: "ITIL: confirma con el usuario, documenta, revisa si es recurrente (KB/problema) y al final haz el cierre formal. Cerrar sin confirmar genera reopens y mala CSAT." },
        { id: "su15", type: "mc", q: "Un change (cambio) controlado implica…", options: ["Ventana, riesgo, aprobación y plan de rollback cuando aplique", "Aplicar el cambio directo en producción y documentarlo solo si falla", "Que el mismo técnico lo apruebe y ejecute, sin revisión ni registro", "Cambiar todo a las 3 a.m. sin aviso ni registro en el ticket"], answer: 0, explain: "CAB/aprobaciones según criticidad. Emergencias tienen proceso aparte." },
        { id: "su16", type: "scenario", q: "Usuario pide la contraseña del admin 'solo un minuto'. Respuesta correcta:", options: ["No compartir credenciales admin; usar vías seguras (LAPS/PAM/elevación)", "Dársela por teléfono y cambiarla cuando el usuario haya terminado", "Añadir al usuario al grupo Domain Admins de forma permanente", "Iniciar sesión tú como admin y dejarle la sesión abierta"], answer: 0, explain: "Nunca compartas root/admin. Ofrece alternativas auditables." }
      ]
    });
  }

  // ——— BOSS battles (incidentes reales) ———
  setBoss("linux", [
    { id: "lxB1", type: "scenario", q: "BOSS: Servidor web caído. df -h muestra / al 100%. ¿Acción inmediata más sensata?", options: ["Liberar espacio (logs/tmp) y revisar qué llena el disco", "Reiniciar el servidor web en bucle hasta que responda", "Aplicar chmod -R 777 / por si es un tema de permisos", "Crear un archivo swap en / para darle más memoria"], answer: 0, explain: "Disco lleno rompe servicios. Identifica con du; rota logs; evita borrados ciegos en /." },
    { id: "lxB2", type: "order", q: "BOSS: Tras liberar disco, ordena validación:", items: ["Comprobar df -h", "Revisar el estado del servicio web", "Probar endpoint/curl local", "Monitorear logs por recidiva"], answer: [0, 1, 2, 3], explain: "Confirma espacio, servicio y funcionalidad antes de cerrar el incidente." },
    { id: "lxB3", type: "mc", q: "BOSS: Proceso en estado D y load alto por I/O. Herramienta útil:", options: ["iotop / iostat / dmesg", "mspaint", "solo colorls", "Event Viewer de Windows en el Linux"], answer: 0, explain: "Investigar I/O wait y errores de disco/SAN antes de matar procesos a ciegas." },
    { id: "lxB4", type: "tf", q: "BOSS: Trabajar siempre como root interactivo es más seguro que usar sudo con auditoría.", answer: false, explain: "Falso: sudo con permisos mínimos y registro reduce errores y deja trazabilidad; una sesión root permanente amplifica cualquier error." },
    { id: "lxB5", type: "fill", q: "BOSS: Comando para ver estado de un servicio systemd llamado nginx:", answer: "systemctl status nginx", accept: ["systemctl status nginx", "systemctl status nginx.service", "sudo systemctl status nginx", "sudo systemctl status nginx.service", "service nginx status", "sudo service nginx status"], explain: "systemctl status|restart|stop|start son el estándar en distros modernas." }
  ]);

  setBoss("windows", [
    { id: "wnB1", type: "scenario", q: "BOSS: Nadie imprime; el print server muestra Spooler detenido. ¿Qué haces?", options: ["Reiniciar Print Spooler, revisar eventos y colas", "Reinstalar los drivers de impresora en cada cliente", "Reiniciar los switches y renovar DHCP en los PCs", "Degradar el nivel funcional de AD y reiniciar los DC"], answer: 0, explain: "Spooler caído = síntoma clásico. Revisa dependencias y fallos recurrentes en Event Viewer." },
    { id: "wnB2", type: "mc", q: "BOSS: Tras reinicio, Event ID de servicio apunta a driver de impresora. Siguiente paso:", options: ["Actualizar/quitar driver problemático; aislar cola", "Ignorar el evento: es informativo y se resuelve solo", "Reinstalar Windows en el servidor de impresión", "Desactivar el archivo de paginación y reiniciar"], answer: 0, explain: "Drivers corruptos tumbaron Spooler históricamente. Aísla el driver culpable." },
    { id: "wnB3", type: "order", q: "BOSS: El PC no se une al dominio tras cambiar credenciales locales. Ordena el diagnóstico:", items: ["Verificar red y que el DNS del equipo apunte al DNS del dominio", "Con el DC localizado, comprobar que la hora coincida (Kerberos)", "Reintentar el join (o reparar el secure channel)", "Si falla, revisar Event Viewer y NetSetup.log"], answer: [0, 1, 2, 3], explain: "Sin el DNS del dominio no se localiza el DC; con el DC localizado, una hora desfasada más de ~5 min rompe Kerberos. Luego reintenta y, si falla, revisa los registros (Event Viewer y %windir%\\debug\\NetSetup.log)." },
    { id: "wnB4", type: "tf", q: "BOSS: ipconfig /renew obtiene una IP nueva aunque el adaptador tenga IP estática.", answer: false, explain: "Falso: /renew solo pide una concesión a DHCP; con IP estática no cambia la configuración manual." },
    { id: "wnB5", type: "identify", q: "BOSS: ¿Dónde miras un BSOD recurrente con detalle?", options: ["Visor de eventos + volcados (dump)", "Administrador de tareas + Monitor de recursos", "Programador de tareas + historial de tareas", "Administración de discos + Desfragmentador"], answer: 0, explain: "Minidumps y Reliability Monitor ayudan a correlacionar drivers." }
  ]);

  setBoss("printers", [
    { id: "prB1", type: "scenario", q: "BOSS TICKET: 40 usuarios; cola \\\\print01\\finanzas Offline. Ping a 10.20.5.50 OK. Puerto 9100 filtrado desde el server. Causa raíz más probable:", options: ["Firewall/ACL bloquea 9100 entre print server e impresora", "Spooler detenido en los PCs de los 40 usuarios", "Falta el registro DNS inverso (PTR) de 10.20.5.50", "Unidad de tambor agotada en la impresora de finanzas"], answer: 0, explain: "ICMP no implica que el servicio de impresión esté permitido. Abre 9100/631 según diseño." },
    { id: "prB2", type: "order", q: "BOSS: Restablecer impresión SMB en planta:", items: ["Validar IP y puertos desde print server", "Detener Spooler en print01", "Limpiar trabajos atascados en spool\\PRINTERS", "Iniciar Spooler, página de prueba y avisar usuarios"], answer: [0, 1, 2, 3], explain: "Red → detener servicio → vaciar cola → iniciar y verificar. Nunca vacíes el spool con el Spooler en ejecución." },
    { id: "prB3", type: "mc", q: "BOSS: Trabajos PCL a impresora solo PS generan:", options: ["Basura/errores de lenguaje; alinear driver (PCL/PS/universal)", "Conversión automática a PostScript en la impresora, sin errores", "Un atasco de papel físico por formato de página erróneo", "Impresión correcta, pero solo en escala de grises"], answer: 0, explain: "Mismatch de PDL es un clásico en flotas mixtas." },
    { id: "prB4", type: "match", q: "BOSS: Empareja protocolo/puerto:", pairs: [
      { left: "IPP", right: "631/tcp" },
      { left: "LPR", right: "515/tcp" },
      { left: "JetDirect raw", right: "9100/tcp" },
      { left: "SMB share", right: "445/tcp (y relacionados)" }
    ], explain: "Conocer puertos acelera firewall y tcpchecks." },
    { id: "prB5", type: "tf", q: "BOSS: Una reserva DHCP para la MAC de la impresora evita que cambie de IP y rompa puertos TCP/IP de clientes.", answer: true, explain: "Estabilidad de dirección = menos tickets 'offline'." },
    { id: "prB6", type: "scenario", q: "BOSS: Drum life exceeded + rayas negras. Acción correcta:", options: ["Reemplazar unidad de tambor / kit mantenimiento según modelo", "Reinstalar el driver y restablecer el contador de páginas", "Actualizar el firmware de la tarjeta de red de la impresora", "Cambiar el tipo de papel en el driver y usar otra bandeja"], answer: 0, explain: "Síntomas de drum no se arreglan con red. Sigue el contador del fabricante." }
  ]);

  setBoss("networks", [
    { id: "netB1", type: "scenario", q: "BOSS: Sucursal sin Internet. LAN interna OK (ping gateway). WAN IP del router 0.0.0.0. ¿Qué revisar?", options: ["Enlace ISP/DHCP WAN/PPPoE/credenciales y cable ONT", "El servidor DHCP de la LAN y los leases de los PCs", "Las VLAN de acceso y el cableado de los switches internos", "La caché DNS de cada PC y el archivo hosts local"], answer: 0, explain: "Gateway LAN responde pero no hay WAN: problema de borde/ISP." },
    { id: "netB2", type: "mc", q: "BOSS: Tras VPN, el usuario llega a servidores pero navega lento. Split tunnel desactivado. Explicación:", options: ["Full tunnel manda también Internet por el datacenter", "El cifrado VPN reduce a la mitad la velocidad del Wi‑Fi", "Sin split tunnel el tráfico se cifra dos veces", "El cable de red local no soporta tráfico cifrado por VPN"], answer: 0, explain: "Sin split tunnel, el ancho de banda del hub limita la web." },
    { id: "netB3", type: "order", q: "BOSS: DNS interno no resuelve app.corp. Ordena:", items: ["Reproducir: nslookup app.corp contra el DNS corporativo", "Acotar: ¿falla también desde otro cliente/segmento?", "Si falla para todos: revisar zona/registro en el DNS server", "Si el nombre no está en una zona local (híbrido): revisar forwarders"], answer: [0, 1, 2, 3], explain: "Reproduce el fallo, acota el alcance (un cliente vs. todos), revisa la zona/registro en el servidor y, si el nombre se resuelve fuera (híbrido), los forwarders. Así separas fallo de cliente vs zona vs forwarder." },
    { id: "netB4", type: "mc", q: "Cliente en VLAN 20 no imprime a VLAN 30. Switch L2 sin routing. ¿Qué falta?", options: ["Enrutamiento entre VLANs (L3) + ACLs que lo permitan", "Un servidor DHCP compartido para las dos VLANs", "Activar PoE en el puerto de la impresora de la VLAN 30", "Desactivar STP en el switch para que las VLAN se vean"], answer: 0, explain: "VLANs distintas necesitan router/SVI y reglas. Un L2 puro no enruta." },
    { id: "netB5", type: "fill", q: "BOSS: Puerto UDP estándar (IANA) de VXLAN (número):", answer: "4789", accept: ["4789", "udp 4789", "udp/4789", "4789/udp"], explain: "VXLAN encapsula tramas L2 en UDP 4789 (IANA). Linux usó 8472 históricamente; si no coincide en ambos extremos, el overlay no levanta." },
    { id: "netB6", type: "tf", q: "BOSS: Un ping fallido no siempre significa que el host esté apagado (ICMP puede estar filtrado).", answer: true, explain: "Complementa con prueba de puerto de aplicación (443, 22, 9100…)." }
  ]);

  setBoss("programming", [
    { id: "pgB1", type: "scenario", q: "BOSS: Prod roto tras deploy. ¿Primera acción sensata?", options: ["Rollback al release anterior y luego investigar", "Seguir pusheando fixes a ciegas sin métricas", "Borrar el repo", "Apagar DNS global"], answer: 0, explain: "Mitiga impacto primero; post‑mortem después." },
    { id: "pgB2", type: "mc", q: "BOSS: TypeError en consola solo en un navegador viejo. Enfoque:", options: ["Reproducir, ver API faltante, transpilar/polyfill o subir requisito", "Reinstalar Node en el servidor y volver a desplegar el mismo build", "Envolver todo en try/catch vacío para que la consola no muestre nada", "Purgar la caché del CDN y asumir que el error desaparecerá solo"], answer: 0, explain: "Compatibilidad = entorno. No asumas que tu Chrome local = todos los usuarios." },
    { id: "pgB3", type: "order", q: "BOSS: Hotfix con git:", items: ["Crear rama desde main estable", "Aplicar fix mínimo + pruebas", "Code review / CI", "Merge y tag de release"], answer: [0, 1, 2, 3], explain: "Cambios mínimos reducen riesgo en incidentes." },
    { id: "pgB4", type: "tf", q: "BOSS: console.log en prod puede filtrar datos sensibles si no se controla.", answer: true, explain: "Evita loguear secretos; usa niveles y redacción." },
    { id: "pgB5", type: "identify", q: "BOSS: ¿Qué sistema guarda historial de cambios del código?", options: ["Git (VCS)", "npm (paquetes)", "Jest (tests)", "Vim (editor)"], answer: 0, explain: "Git permite blame, revert y branches de emergencia." }
  ]);

  setBoss("support", [
    { id: "suB1", type: "scenario", q: "BOSS: P1 — correo caído para toda la empresa. Tú eres N1. ¿Qué haces primero?", options: ["Declarar incidente mayor, comunicar, escalar N2/messaging y seguir runbook", "Pedir a cada usuario que reinicie su PC y reabra Outlook", "Reiniciar tú mismo el servidor de correo sin avisar ni registrar nada", "Atender los tickets uno a uno según orden de llegada"], answer: 0, explain: "P1 = comunicación + bridge + escalamiento. No inventes fixes masivos sin runbook." },
    { id: "suB2", type: "order", q: "BOSS: Gestión de crisis N1:", items: ["Confirmar síntomas y alcance (usuarios/servicios)", "Declarar P1: abrir bridge y avisar stakeholders", "Ejecutar pasos N1 del runbook / escalar", "Actualizar status cada X minutos hasta resolver"], answer: [0, 1, 2, 3], explain: "Confirma el alcance para clasificar, declara y comunica de inmediato, actúa con el runbook y no dejes de actualizar: silencio en un P1 destruye confianza." },
    { id: "suB3", type: "mc", q: "BOSS: Usuario VIP exige salto de cola para un wallpaper. ¿Respuesta?", options: ["Explicar prioridad con respeto; no romper P1 reales; ofrecer request normal", "Pausar los P1 abiertos y atender primero al VIP por su cargo", "Darle permisos de administrador para que cambie el wallpaper él mismo", "Aceptar y prometerle un ETA que no podrás cumplir"], answer: 0, explain: "Prioridad objetiva > ego. Escala políticas a tu lead si hay presión." },
    { id: "suB4", type: "tf", q: "BOSS: Documentar workarounds en KB reduce tickets repetidos.", answer: true, explain: "Deflecta carga N1 y estandariza respuestas." },
    { id: "suB5", type: "match", q: "BOSS: Empareja acción con principio:", pairs: [
      { left: "No compartir admin", right: "Seguridad / mínimo privilegio" },
      { left: "Confirmar cierre", right: "Calidad de servicio" },
      { left: "Escalar con logs", right: "Handoff efectivo" },
      { left: "SLA", right: "Tiempos acordados" }
    ], explain: "Soporte excelente = técnica + proceso + ética." }
  ]);
})();
